package com.example.a2;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class sysTest {
    
    private Sys system;

    @BeforeEach
    public void setUp() {
        system = new Sys();
    }

    //---------------------------------------------
    @Test
    void testAdminWriteExistingCountry() {
        assertEquals(1,1);
    }
}

